config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"


  get "/welcome", to: "welcome#index"
  resources :questions, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.all
  end

  def show
    @question = Question.find(params[:id])
    # takes the presidents name and sends it to js w/ Gon gem
    @answer = @question.name.downcase
    gon.answer = cipher(@answer)
    gon.id = @question.id

  end

  def cipher(answer)
    arr = answer.split(%r{\s*})
    arr.map!{ |i| (i.ord + 3).chr }
  end

  def new
    @question = Question.new
  end

  def answer
    @question = Question.where(name: params[:guess])
  end
  

  private
    def article_params
      params.require(:question).permit(:name)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnPresidents</title>
    <%= Gon::Base.render_data %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= yield %>
  
  </body>
</html>

app/views/questions/index.html.erb
<div class = 'pres_table' style='width: 15%; margin-left: 0px; text-align: left;'>
  <%= 'Choose any president to start at:'%>
  <div style = 'padding: 2px; background-color: white; border: 1px solid black;'>
    <% @question.each do |question| %>
      <%= link_to "President ##{question.id}", question_path(question) %> <br>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class = 'pres_table'>
  <div id = 'pres_label'>
    <%= "PRESIDENT NUMBER" %><br>
  </div>
  <div id = 'pres_number'>
    <%= @question.id %>
  </div>
  <div>
    <%= @question.years %>
  </div>
</div><br>



<div class='pres_table'>
    <%= "Enter your guess: "%>
    <input type = "text_area", id = 'guess_input'>
    <button id='guess_button'> Submit </button>
</div><br>

<div id = 'hint_table'>
  <div>
    <%= "There are three hints of increasing obviousness for each president."%>
  </div>
  <div class = 'hint-button'>
    <button id = 'hint'> HINT </button>
  </div>
  <br>

  <div>
    <div id = 'hint-1'>
      <%= @question.hint_1 %>
    </div>
    <br>
    <div id = 'hint-2'>
      <%= @question.hint_2 %> 
    </div>
    <br>
    <div id = 'hint-3'>
      <%= @question.hint_3 %> 
    </div>
</div>



<%= javascript_pack_tag 'question'  %>

app/views/welcome/index.html.erb
<div class = 'pres_table'>
  <div id = 'welcome_banner_h'>
    <%= 'This site is easiest way to learn every U.S.A. president.'%>
  </div>
  <div id='welcome_text'>
    <%= "Begin learning right now with \'Quick Start\' or choose where to start by clicking on \'Questions.\'"%>
  </div> <br>
  <div>
    <%= link_to "Start Quiz", "questions/1/", class: 'start' %>

    <%= link_to "Questions", "questions/", class: 'start' %>
  </div>
</div>